package me.nicolas.adventofcode.year2025

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class Day07Test {
    private val day = Day07(2025, 7)
    
    val test = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent()

    @Test
    fun partOne() {
        assertEquals(21, day.partOne(test))
    }

    @Test
    fun partTwo() {
        assertEquals(40, day.partTwo(test))
    }
}